name: Docker Deploy to DockerHub

on:
  push:
    branches:
      - master  # Ensure this matches your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Debug: Display Docker version and available images
      - name: Debug Docker setup
        run: |
          docker --version
          docker images

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use the secret for Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use the secret for Docker Hub password

      # Build and push Docker image
      - name: Build and Push Docker image
        run: |
          echo "Building the Docker image..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .
          
          echo "Pushing the Docker image..."
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
